backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "intro" # Used in routes, e.g., /admin/collections/intro
    label: "Intro Section" # Used in the UI
    folder: "static/_intro" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "intro" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "List 1", name: "list1", widget: "string" }
      - label: "List 1 Items "
        name: "list1items"
        collapsed: false
        widget: "list"
        fields:
          - { label: Item, name: item, widget: string }
      - { label: "List 2", name: "list2", widget: "string" }
      - label: "List 2 Items "
        name: "list2items"
        collapsed: false
        widget: "list"
        fields:
          - { label: Item, name: item, widget: string }
  - name: "media" # Used in routes, e.g., /admin/collections/media
    label: "Media" # Used in the UI
    folder: "static/_media" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "media"}
      - { label: "Image", name: "image", widget: "image" } 